"use client"
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './components/Header'
import Footer from './components/Footer'
import { RecoilRoot } from 'recoil'

const inter = Inter({ subsets: ['latin'] })

 const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <RecoilRoot>        
      <body className={inter.className}>
        <Header></Header>
        {children}
        <Footer></Footer>
        </body>
        </RecoilRoot>  
    </html>
  )
}
